/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type ReligionTrait = 'Mistical' | 'Prophetic' | 'Activist' | 'Syncretist';

export type CountryTag = 'Secular' | 'Devoto' | 'Autoritário' | 'Tribal' | 'Progressista' | 'Militarista';

export type VictoryGoalType = 'GlobalEcstasy' | 'PerpetualPeace' | 'OneFlock' | 'TheEnlightened';

export interface Country {
  id: string;
  name: string;
  population: number;
  converts: number;         // raw count of followers
  resistance: number;       // from 0 to 100 (percentage)
  violence: number;         // from 0 to 100 (percentage)
  leaderInfiltration: number; // 0 to 100 (progress of leader conversion)
  leaderName: string;
  regimeType: 'opressor' | 'teocracia' | 'democracia' | 'autoritario' | 'liberal' | 'vibrante' | 'estavel';
  specialTrait: string;
  specialTraitDesc: string;
  coordinates: { x: number; y: number }; // for map visual rendering
  missionariesSent: number;
  temples: number[];           // [l1count, l2count, l3count, l4count] completed temples per level
  templesBuilding: number[];   // count currently being built per level
  templesBuildCycles: number[]; // shared countdown per level (all pending at that level complete together)
  templeSpec: 'conversion' | 'resistance' | null; // specialization unlocked after first level-2 temple
  cyclesPresent: number; // cycles with at least 1 convert (for linguistic barrier)
  lastConflictCycle: number; // last cycle a group conflict fired in this country
  localReligionStrength: number; // 0-100: strength of competing local religion/ideology
  tags: CountryTag[]; // personality tags affecting gameplay mechanics
  lastActionCycle: number; // last cycle the player took an action in this country (for inactivity decay)
  convertsHistory: number[]; // rolling history of convert counts (last 50 cycles)
  coupDone?: boolean; // true if this country's regime was converted via a player coup
}

export interface Dogma {
  id: string;
  name: string;
  description: string;
  costFaith: number;
  costFervor: number;
  purchased: boolean;
  traitRequirement?: ReligionTrait;
  effect: string;
  phase: 1 | 2 | 3;
}

export interface GameEvent {
  id: string;
  title: string;
  description: string;
  impactType: 'bonus' | 'penalty' | 'neutral' | 'prophecy' | 'ecstasy' | 'persecution';
  traitRequirement?: ReligionTrait;
  actionEffects: {
    globalFaithMod?: number;
    globalFervorMod?: number;
    countryConvertsMod?: { [countryId: string]: number }; // absolute value change
    countryConvertsModPct?: { [countryId: string]: number }; // percentage loss (negative = loss)
    globalConvertsModPct?: number; // percentage loss applied to all countries with converts
    countryResistanceMod?: { [countryId: string]: number };
    countryViolenceMod?: { [countryId: string]: number };
    globalFaithCostMod?: number; // one-time faith drain
  };
}

export interface DoctrineChoice {
  id: string;
  topic: string;
  section: 'universal' | 'social';
  tier: 'basic' | 'intermediate' | 'strategic';
  optionA: { label: string; effectDesc: string; };
  optionB: { label: string; effectDesc: string; };
  chosen: 'A' | 'B' | null;
}

export interface GameState {
  started: boolean;
  religionName: string;
  religionTrait: ReligionTrait;
  victoryGoal: VictoryGoalType;
  faith: number;
  fervor: number;
  cycle: number;
  paused: boolean;
  gameSpeed: 1 | 2 | 3;
  selectedCountryId: string | null;
  dogmas: Dogma[];
  countries: Country[];
  eventActive: GameEvent | null;
  rivalProgress: number; // 0 to 100 % towards rival victory
  rivalName: string;
  resistanceStreak: number; // counts consecutive cycles with global average resistance > 85%
  isGameOver: boolean;
  gameOverReason: 'victory' | 'resistance' | 'bankrupt' | 'rival' | null;
  totalTemples: number;
  lastEventCycle: number; // cycle number when the last random event was triggered
  lastEventTimestamp: number; // ms timestamp of the last event (for 2-min global cooldown)
  eventCooldowns: { [eventId: string]: number }; // cycle number each event last fired (individual 25-cycle cooldown)
  doctrines: DoctrineChoice[];
  tithe: number; // financial resource generated by faithful, spent on infrastructure
  faithPhase: 1 | 2 | 3; // progression phase: 1=Centelha, 2=Credo, 3=Transcendência
  firstCountryConverted: string | null; // country name of first country to reach meaningful presence
  peakFervor: number; // highest fervor reached this run
  lastEcstasyRitual: number; // cycle of last ecstasy ritual (cooldown tracking)
  faithBankruptStreak: number; // consecutive cycles with faith <= 5 (bankruptcy detection)
}
