/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type ReligionTrait = 'Mistical' | 'Prophetic' | 'Activist' | 'Syncretist';

export type VictoryGoalType = 'GlobalEcstasy' | 'PerpetualPeace' | 'OneFlock' | 'TheEnlightened';

export interface Country {
  id: string;
  name: string;
  population: number;
  converts: number;         // raw count of followers
  resistance: number;       // from 0 to 100 (percentage)
  violence: number;         // from 0 to 100 (percentage)
  leaderInfiltration: number; // 0 to 100 (progress of leader conversion)
  leaderName: string;
  regimeType: 'opressor' | 'teocracia' | 'democracia' | 'autoritario' | 'liberal' | 'vibrante' | 'estavel';
  specialTrait: string;
  specialTraitDesc: string;
  coordinates: { x: number; y: number }; // for map visual rendering
  missionariesSent: number;
  templeLevel: number; // 0 = none, 1-4 = temple tier
  templePending: number; // 0 = no pending build; 1-4 = level being built
  templeBuildCyclesLeft: number; // cycles remaining until templePending completes
  templeSpec: 'conversion' | 'resistance' | null; // chosen specialization at level 2+
  cyclesPresent: number; // cycles with at least 1 convert (for linguistic barrier)
  lastConflictCycle: number; // last cycle a group conflict fired in this country
  localReligionStrength: number; // 0-100: strength of competing local religion/ideology
}

export interface Dogma {
  id: string;
  name: string;
  description: string;
  costFaith: number;
  costFervor: number;
  purchased: boolean;
  traitRequirement?: ReligionTrait;
  effect: string;
}

export interface GameEvent {
  id: string;
  title: string;
  description: string;
  impactType: 'bonus' | 'penalty' | 'neutral' | 'prophecy' | 'ecstasy' | 'persecution';
  traitRequirement?: ReligionTrait;
  actionEffects: {
    globalFaithMod?: number;
    globalFervorMod?: number;
    countryConvertsMod?: { [countryId: string]: number }; // percentage or absolute
    countryResistanceMod?: { [countryId: string]: number };
    countryViolenceMod?: { [countryId: string]: number };
  };
}

export interface DoctrineChoice {
  id: string;
  topic: string;
  section: 'universal' | 'social';
  tier: 'basic' | 'intermediate' | 'strategic';
  optionA: { label: string; effectDesc: string; };
  optionB: { label: string; effectDesc: string; };
  chosen: 'A' | 'B' | null;
}

export interface GameState {
  started: boolean;
  religionName: string;
  religionTrait: ReligionTrait;
  victoryGoal: VictoryGoalType;
  faith: number;
  fervor: number;
  cycle: number;
  paused: boolean;
  gameSpeed: 1 | 2 | 3;
  selectedCountryId: string | null;
  dogmas: Dogma[];
  countries: Country[];
  logs: string[];
  eventActive: GameEvent | null;
  rivalProgress: number; // 0 to 100 % towards rival victory
  rivalName: string;
  resistanceStreak: number; // counts consecutive cycles with global average resistance > 85%
  isGameOver: boolean;
  gameOverReason: 'victory' | 'resistance' | 'bankrupt' | 'rival' | null;
  totalTemples: number;
  lastEventCycle: number; // cycle number when the last random event was triggered
  lastEventTimestamp: number; // ms timestamp of the last event (for 2-min global cooldown)
  eventCooldowns: { [eventId: string]: number }; // cycle number each event last fired (individual 25-cycle cooldown)
  doctrines: DoctrineChoice[];
  tithe: number; // financial resource generated by faithful, spent on infrastructure
}
